### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by nicoh88** [materik/homebridge-harmonyhub-plugin#12]
Why have not you released your plugin with NPM yet?

Then `npm -g outdated --long` would also run properly and display when there is a new version.

**Comment by materik** [comment]
I should. Wanted to wait before it felt more stable. Might be good time to tho :)

**Comment by nicoh88** [comment]
Compared to what others publish, yours is awesome.

**Comment by materik** [comment]
I'll wait for one other person to confirm the solution to #8 and after it has been closed I will publish :+1:

**Comment by materik** [comment]
it's published 🥳 https://www.npmjs.com/package/@materik/homebridge-harmonyhub

**Comment by nicoh88** [comment]
Uh, problem.

With `npm install -g @materik/homebridge-harmonyhub` the packages becomes installed in `/usr/lib/node_modules/@materik/homebridge-harmonyhub`.

Homebridge doesn't found the plugin...

```
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
```

**Comment by materik** [comment]
you're right. the problem is HomeBridge cannot find the plugin if it's within two folders. would have though UPDATE1 would solve it. the easiest fix is probably to rename the package but not sure what to call it then since `homebridge-harmonyhub` is taken :P

**Comment by materik** [comment]
changed the name to `homebridge-harmonyhub-plugin` which can now be installed by `npm install -g  homebridge-harmonyhub-plugin`. the `@materik/homebridge-harmonyhub` package has been removed.
