### ISSUE TITLE
harmonyhub:discover:responsecollector handle new connection

### ISSUE THREAD

**Issue by pgrill79** [materik/homebridge-harmonyhub-plugin#13]
I have installed the latest firmware 4.15.210 which enables the API on Harmony Hub again.

see here:
https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

Actually everything works fine and i get all the actions on my harmony:

[2019-1-26 14:22:29] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
[2019-1-26 14:22:29] [homebridge-harmonyhub-plugin] {HarmonyHub} 
[2019-1-26 14:22:30] [homebridge-harmonyhub-plugin] {HarmonyHub} create new client for 
[2019-1-26 14:22:31] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <2> activities: <Apple, Fernsehen>

but nevertheless i get errors every second in the error log - which leads that the error log grows very fast and fills the HDD:

These 4 messages appear every second:

2019-01-26T13:22:59.692Z harmonyhub:discover:responsecollector handle new connection
2019-01-26T13:22:59.696Z harmonyhub:discover:responsecollector received data chunk
2019-01-26T13:22:59.696Z harmonyhub:discover:responsecollector connection closed. emitting data
2019-01-26T13:23:00.475Z harmonyhub:discover:ping emit()

It is the same behaviour i have with the homebridge-harmonyhub plugin. Also there i was able to get all the actions and the plugin works basically fine, but because spamming the error log the processor works all the time and the error log grows until hdd is full (which stops raspberry to not startup anymore)

Any idea ?

**Comment by materik** [comment]
Hmm. Are you running with some kind of debug logging? I am not seeing this myself.

**Comment by AirBorne04** [comment]
hi @pgrill79 you have set the `DEBUG` environment var to `harmonyhub:discover` therefore you do get the log of the `@harmonyhub/discover` package (exactly what you have posted above). Try `export DEBUG=""` to remove the logging, btw this is not the error log :)

**Comment by pgrill79** [comment]
Hi @AirBorne04 , @materik:

i checked the env variables and i haven't had a DEBUG entry at all - then i tried to set it to "" with the export command. (i also rebooted the raspi afterwards)

Then i see:

[...]
SUDO_GID=1000
DISPLAY=:10.0
DEBUG=
USERNAME=root
[...]

if i type "env" to the command line. (i also added it to the /etc/profile to be set everytime when restarting)

But nevertheless i still get these messages in the "homebridge.err" file. :(

**Comment by materik** [comment]
I'm sorry you're having problem. Are you still experience this or is there something I can look into not having experienced this myself.

**Comment by AirBorne04** [comment]
Hi @pgrill79,
i was checking a little bit more and can't seem to be able to find a reason for this behavior, which command are you using to start your homebridge service?

**Comment by materik** [comment]
@pgrill79 since this issue has become a bit stale i'm closing it. please let me know if you want to reopen it with more details to look into. thanks!
