### ISSUE TITLE
Addition to readme

### ISSUE THREAD

**Issue by Pensive** [materik/homebridge-harmonyhub-plugin#14]
Can I suggest for clarity you include in the readme that:
1) This plugin works locally using XMPP
2) This requires that your hub is firmware flashed to the beta XMPP supported firmware version 4.15.206 via the desktop harmony tool

Just so that everyone is clear - and once they've finally provided XMPP access again in the main builds it can be removed :)

Thanks for the plugin - flashing my firmware now - hopefully it will all work swimmingly :)

**Comment by materik** [comment]
But this project doesn't rely on xmpp anymore since I change the harmony dependency to https://github.com/AirBorne04/harmonyhub/tree/develop/packages/client-ws. Or I'm I missing something?

**Comment by Pensive** [comment]
Ah....

I want to remain local - I thought this used xmpp. I’ve enabled it as a beta function.

Thanks but I don’t want to link in an external server dependency into my smart home system.

Can you mention it uses websockets

**Comment by materik** [comment]
sure
