### ISSUE TITLE
New TV interface?

### ISSUE THREAD

**Issue by homohurre123** [materik/homebridge-harmonyhub-plugin#15]
Will there be an update where we can use the new added tv interfaces or is it impossible with Harmony ?

**Comment by materik** [comment]
Will have a look

**Comment by materik** [comment]
I looked through what you can do with the TV interface and it isn't really compatible with what you can do with Harmony Hub. Think the Switch is the best accessory for now.

**Comment by RXM307** [comment]
Looks like there's another fork that has already implemented this functionality it might be worth porting in the changes? https://github.com/nicoduj/homebridge-harmony
