### ISSUE TITLE
Question when setting up a "Done watching TV scene"

### ISSUE THREAD

**Issue by pponce** [materik/homebridge-harmonyhub-plugin#18]
I have 5 activities and i'd like to have just one "done watching" scene.
If I place all 5 activities in the scene to turn off, will it send the off event 5 times?
or will it just send the off command for the one activity that is actually on?
Does it make sense to expose a generic "turn off" any activity switch?

**Comment by materik** [comment]
In my home app i have a "Turn Off TV" scene which switches off all related harmony activities. This works. I don't remember if I did a check or if the harmony hub doesn't except a turn off activity if it's already off.
