### ISSUE TITLE
may want to update readme / add instructions for new firmware 4.15.250

### ISSUE THREAD

**Issue by dVIAN13** [materik/homebridge-harmonyhub-plugin#20]
see https://community.logitech.com/s/question/0D55A00008OsX3CSAV/update-to-accessing-harmony-hubs-local-api-via-xmpp..

I think adding a note that mentions enabling XMPP access is required..

**Comment by materik** [comment]
this package currently uses web sockets but might switch back to XMPP in the future if my dependencies permit.
