### ISSUE TITLE
Problems with FW 4.15.250

### ISSUE THREAD

**Issue by mensa84** [materik/homebridge-harmonyhub-plugin#21]
Hello,

since Harmony Hub Firmware 4.15.250 the plugin throws a lot of errors and can not control Harmony activities or even get correct state.

XMPP for all my Hubs is enabled in new App/FW version.

Will there be a fix soon please?

**Comment by mensa84** [comment]
These are the errors at homebridge startup with Harmony Hubs on FW 4.15.250:

`Feb 19 01:15:24 Server homebridge[9076]: [2/19/2019, 1:15:24 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <2> hubs
Feb 19 01:15:24 Server homebridge[9076]: [2/19/2019, 1:15:24 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} <762da678-4cdb-48f7-8236-b407edd3d714> <Harmony Wohnzimmer>
Feb 19 01:15:24 Server homebridge[9076]: [2/19/2019, 1:15:24 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} <33a61542-f94e-44ed-9c95-c257625a7a00> <Harmony Schlafzimmer>
Feb 19 01:15:24 Server homebridge[9076]: [2/19/2019, 1:15:24 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: { HTTPError: Response code 417 (Expectation Failed)
Feb 19 01:15:24 Server homebridge[9076]:     at EventEmitter.emitter.on (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/got/source/as-promise.js:74:19)
Feb 19 01:15:24 Server homebridge[9076]:     at processTicksAndRejections (internal/process/next_tick.js:81:5)
Feb 19 01:15:24 Server homebridge[9076]:   name: 'HTTPError',
Feb 19 01:15:24 Server homebridge[9076]:   host: '192.168.1.20:8088',
Feb 19 01:15:24 Server homebridge[9076]:   hostname: '192.168.1.20',
Feb 19 01:15:24 Server homebridge[9076]:   method: 'POST',
Feb 19 01:15:24 Server homebridge[9076]:   path: '/',
Feb 19 01:15:24 Server homebridge[9076]:   socketPath: undefined,
Feb 19 01:15:24 Server homebridge[9076]:   protocol: 'http:',
Feb 19 01:15:24 Server homebridge[9076]:   url: 'http://192.168.1.20:8088/',
Feb 19 01:15:24 Server homebridge[9076]:   gotOptions:
Feb 19 01:15:24 Server homebridge[9076]:    { path: '/',
Feb 19 01:15:24 Server homebridge[9076]:      protocol: 'http:',
Feb 19 01:15:24 Server homebridge[9076]:      slashes: true,
Feb 19 01:15:24 Server homebridge[9076]:      auth: null,
Feb 19 01:15:24 Server homebridge[9076]:      host: '192.168.1.20:8088',
Feb 19 01:15:24 Server homebridge[9076]:      port: '8088',
Feb 19 01:15:24 Server homebridge[9076]:      hostname: '192.168.1.20',
Feb 19 01:15:24 Server homebridge[9076]:      hash: null,
Feb 19 01:15:24 Server homebridge[9076]:      search: null,
Feb 19 01:15:24 Server homebridge[9076]:      query: null,
Feb 19 01:15:24 Server homebridge[9076]:      pathname: '/',
Feb 19 01:15:24 Server homebridge[9076]:      href: 'http://192.168.1.20:8088/',
Feb 19 01:15:24 Server homebridge[9076]:      retry:
Feb 19 01:15:24 Server homebridge[9076]:       { retries: [Function],
Feb 19 01:15:24 Server homebridge[9076]:         methods: [Set],
Feb 19 01:15:24 Server homebridge[9076]:         statusCodes: [Set],
Feb 19 01:15:24 Server homebridge[9076]:         errorCodes: [Set],
Feb 19 01:15:24 Server homebridge[9076]:         maxRetryAfter: 5000 },
Feb 19 01:15:24 Server homebridge[9076]:      headers:
Feb 19 01:15:24 Server homebridge[9076]:       { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
Feb 19 01:15:24 Server homebridge[9076]:         'content-type': 'application/json',
Feb 19 01:15:24 Server homebridge[9076]:         accept: 'text/plain',
Feb 19 01:15:24 Server homebridge[9076]:         origin: 'http//:localhost.nebula.myharmony.com',
Feb 19 01:15:24 Server homebridge[9076]:         'accept-encoding': 'gzip, deflate',
Feb 19 01:15:24 Server homebridge[9076]:         'content-length': 54 },
Feb 19 01:15:24 Server homebridge[9076]:      hooks:
Feb 19 01:15:24 Server homebridge[9076]:       { beforeRequest: [],
Feb 19 01:15:24 Server homebridge[9076]:         beforeRedirect: [],
Feb 19 01:15:24 Server homebridge[9076]:         beforeRetry: [],
Feb 19 01:15:24 Server homebridge[9076]:         afterResponse: [],
Feb 19 01:15:24 Server homebridge[9076]:         beforeError: [],
Feb 19 01:15:24 Server homebridge[9076]:         init: [] },
Feb 19 01:15:24 Server homebridge[9076]:      decompress: true,
Feb 19 01:15:24 Server homebridge[9076]:      throwHttpErrors: true,
Feb 19 01:15:24 Server homebridge[9076]:      followRedirect: true,
Feb 19 01:15:24 Server homebridge[9076]:      stream: false,
Feb 19 01:15:24 Server homebridge[9076]:      form: false,
Feb 19 01:15:24 Server homebridge[9076]:      json: true,
Feb 19 01:15:24 Server homebridge[9076]:      cache: false,
Feb 19 01:15:24 Server homebridge[9076]:      useElectronNet: false,
Feb 19 01:15:24 Server homebridge[9076]:      method: 'POST',
Feb 19 01:15:24 Server homebridge[9076]:      body: '{"id":0,"cmd":"connect.discoveryinfo?get","params":{}}',
Feb 19 01:15:24 Server homebridge[9076]:      gotTimeout: { request: 5000 } },
Feb 19 01:15:24 Server homebridge[9076]:   statusCode: 417,
Feb 19 01:15:24 Server homebridge[9076]:   statusMessage: 'Expectation Failed',
Feb 19 01:15:24 Server homebridge[9076]:   headers:
Feb 19 01:15:24 Server homebridge[9076]:    { 'access-control-allow-headers': 'origin, content-type, accept',
Feb 19 01:15:24 Server homebridge[9076]:      'access-control-allow-method': 'POST, OPTIONS',
Feb 19 01:15:24 Server homebridge[9076]:      'access-control-allow-origin': 'http//:localhost.nebula.myharmony.com',
Feb 19 01:15:24 Server homebridge[9076]:      'content-length': '16' },
Feb 19 01:15:25 Server homebridge[9076]:   body: { code: '417' } }
Feb 19 01:15:25 Server homebridge[9076]: [2/19/2019, 1:15:24 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: TypeError: Cannot read property 'getActivities' of undefined
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:130:27
Feb 19 01:15:25 Server homebridge[9076]:     at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
Feb 19 01:15:25 Server homebridge[9076]:     at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
Feb 19 01:15:25 Server homebridge[9076]:     at processTicksAndRejections (internal/process/next_tick.js:74:9)
Feb 19 01:15:25 Server homebridge[9076]: [2/19/2019, 1:15:24 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: TypeError: Cannot read property 'getCurrentActivity' of undefined
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:178:27
Feb 19 01:15:25 Server homebridge[9076]:     at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
Feb 19 01:15:25 Server homebridge[9076]:     at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
Feb 19 01:15:25 Server homebridge[9076]:     at processTicksAndRejections (internal/process/next_tick.js:74:9)
Feb 19 01:15:25 Server homebridge[9076]: [2/19/2019, 1:15:25 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: { HTTPError: Response code 417 (Expectation Failed)
Feb 19 01:15:25 Server homebridge[9076]:     at EventEmitter.emitter.on (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/got/source/as-promise.js:74:19)
Feb 19 01:15:25 Server homebridge[9076]:     at processTicksAndRejections (internal/process/next_tick.js:81:5)
Feb 19 01:15:25 Server homebridge[9076]:   name: 'HTTPError',
Feb 19 01:15:25 Server homebridge[9076]:   host: '192.168.1.30:8088',
Feb 19 01:15:25 Server homebridge[9076]:   hostname: '192.168.1.30',
Feb 19 01:15:25 Server homebridge[9076]:   method: 'POST',
Feb 19 01:15:25 Server homebridge[9076]:   path: '/',
Feb 19 01:15:25 Server homebridge[9076]:   socketPath: undefined,
Feb 19 01:15:25 Server homebridge[9076]:   protocol: 'http:',
Feb 19 01:15:25 Server homebridge[9076]:   url: 'http://192.168.1.30:8088/',
Feb 19 01:15:25 Server homebridge[9076]:   gotOptions:
Feb 19 01:15:25 Server homebridge[9076]:    { path: '/',
Feb 19 01:15:25 Server homebridge[9076]:      protocol: 'http:',
Feb 19 01:15:25 Server homebridge[9076]:      slashes: true,
Feb 19 01:15:25 Server homebridge[9076]:      auth: null,
Feb 19 01:15:25 Server homebridge[9076]:      host: '192.168.1.30:8088',
Feb 19 01:15:25 Server homebridge[9076]:      port: '8088',
Feb 19 01:15:25 Server homebridge[9076]:      hostname: '192.168.1.30',
Feb 19 01:15:25 Server homebridge[9076]:      hash: null,
Feb 19 01:15:25 Server homebridge[9076]:      search: null,
Feb 19 01:15:25 Server homebridge[9076]:      query: null,
Feb 19 01:15:25 Server homebridge[9076]:      pathname: '/',
Feb 19 01:15:25 Server homebridge[9076]:      href: 'http://192.168.1.30:8088/',
Feb 19 01:15:25 Server homebridge[9076]:      retry:
Feb 19 01:15:25 Server homebridge[9076]:       { retries: [Function],
Feb 19 01:15:25 Server homebridge[9076]:         methods: [Set],
Feb 19 01:15:25 Server homebridge[9076]:         statusCodes: [Set],
Feb 19 01:15:25 Server homebridge[9076]:         errorCodes: [Set],
Feb 19 01:15:25 Server homebridge[9076]:         maxRetryAfter: 5000 },
Feb 19 01:15:25 Server homebridge[9076]:      headers:
Feb 19 01:15:25 Server homebridge[9076]:       { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
Feb 19 01:15:25 Server homebridge[9076]:         'content-type': 'application/json',
Feb 19 01:15:25 Server homebridge[9076]:         accept: 'text/plain',
Feb 19 01:15:25 Server homebridge[9076]:         origin: 'http//:localhost.nebula.myharmony.com',
Feb 19 01:15:25 Server homebridge[9076]:         'accept-encoding': 'gzip, deflate',
Feb 19 01:15:25 Server homebridge[9076]:         'content-length': 54 },
Feb 19 01:15:25 Server homebridge[9076]:      hooks:
Feb 19 01:15:25 Server homebridge[9076]:       { beforeRequest: [],
Feb 19 01:15:25 Server homebridge[9076]:         beforeRedirect: [],
Feb 19 01:15:25 Server homebridge[9076]:         beforeRetry: [],
Feb 19 01:15:25 Server homebridge[9076]:         afterResponse: [],
Feb 19 01:15:25 Server homebridge[9076]:         beforeError: [],
Feb 19 01:15:25 Server homebridge[9076]:         init: [] },
Feb 19 01:15:25 Server homebridge[9076]:      decompress: true,
Feb 19 01:15:25 Server homebridge[9076]:      throwHttpErrors: true,
Feb 19 01:15:25 Server homebridge[9076]:      followRedirect: true,
Feb 19 01:15:25 Server homebridge[9076]:      stream: false,
Feb 19 01:15:25 Server homebridge[9076]:      form: false,
Feb 19 01:15:25 Server homebridge[9076]:      json: true,
Feb 19 01:15:25 Server homebridge[9076]:      cache: false,
Feb 19 01:15:25 Server homebridge[9076]:      useElectronNet: false,
Feb 19 01:15:25 Server homebridge[9076]:      method: 'POST',
Feb 19 01:15:25 Server homebridge[9076]:      body: '{"id":0,"cmd":"connect.discoveryinfo?get","params":{}}',
Feb 19 01:15:25 Server homebridge[9076]:      gotTimeout: { request: 5000 } },
Feb 19 01:15:25 Server homebridge[9076]:   statusCode: 417,
Feb 19 01:15:25 Server homebridge[9076]:   statusMessage: 'Expectation Failed',
Feb 19 01:15:25 Server homebridge[9076]:   headers:
Feb 19 01:15:25 Server homebridge[9076]:    { 'access-control-allow-headers': 'origin, content-type, accept',
Feb 19 01:15:25 Server homebridge[9076]:      'access-control-allow-method': 'POST, OPTIONS',
Feb 19 01:15:25 Server homebridge[9076]:      'access-control-allow-origin': 'http//:localhost.nebula.myharmony.com',
Feb 19 01:15:25 Server homebridge[9076]:      'content-length': '16' },
Feb 19 01:15:25 Server homebridge[9076]:   body: { code: '417' } }
Feb 19 01:15:25 Server homebridge[9076]: [2/19/2019, 1:15:25 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: TypeError: Cannot read property 'getActivities' of undefined
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:130:27
Feb 19 01:15:25 Server homebridge[9076]:     at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
Feb 19 01:15:25 Server homebridge[9076]:     at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
Feb 19 01:15:25 Server homebridge[9076]:     at processTicksAndRejections (internal/process/next_tick.js:74:9)
Feb 19 01:15:25 Server homebridge[9076]: [2/19/2019, 1:15:25 AM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: TypeError: Cannot read property 'getCurrentActivity' of undefined
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/harmonyhub.js:178:27
Feb 19 01:15:25 Server homebridge[9076]:     at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
Feb 19 01:15:25 Server homebridge[9076]:     at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
Feb 19 01:15:25 Server homebridge[9076]:     at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
Feb 19 01:15:25 Server homebridge[9076]:     at processTicksAndRejections (internal/process/next_tick.js:74:9)
`

**Comment by materik** [comment]
ok. will have a look.

**Comment by xMAIKx** [comment]
Hello, it does not work for me anymore. Is it perhaps with the new npm version together?

**Comment by mensa84** [comment]
I have the same problems with npm 6.7.0 and 6.8.0.

**Comment by jeffqchen** [comment]
Same problem here, Logitech at work yet again.

**Comment by x5nder** [comment]
Same here; enabled XMPP access on firmware 4.15.250 but the plugin crashes. Hope you can fix this soon :-(

**Comment by mensa84** [comment]
Any progress on this?

**Comment by materik** [comment]
@mensa84 I'm having a look now.

**Comment by materik** [comment]
I've tried to update some packages but it seems to be deeper rooted than what i'm capable of fixing. Maybe @AirBorne04 has some ideas.

**Comment by recipriversexcluson** [comment]
I love this tool. Is there any way to revert to an old working version? It only stopped working when I updated.

**Comment by recipriversexcluson** [comment]
It works here. Latest firmware and enabled XMPP.

**Comment by xMAIKx** [comment]
That can not be. It does not work here.

**Comment by recipriversexcluson** [comment]
That's unusual. What could be different?

**Comment by AirBorne04** [comment]
hi, i did not verify yet that the `xmpp` client is working again correctly. But afaik this plugin is running with the `websocket` version which should not have been changed in any way since the update, but i will validate both plugins and apply possibly needed fixes.

**Comment by mmutreja** [comment]
I am seeing the exact same exceptions with firmware 250.  XMPP enabled

**Comment by AirBorne04** [comment]
hi @materik i have fixed the client-ws lib so it should work fine again with the latest hub firmware.

**Comment by materik** [comment]
@AirBorne04 Super!

**Comment by materik** [comment]
@mensa84 try installing `npm install -g materik/homebridge-harmony-plugin#develop` and see if that works. I haven't tested it myself yet but will do when I get home.

**Comment by mensa84** [comment]
Hello, when I try that command, I get that error:

```
root@Server:~# npm install -g materik/homebridge-harmony-plugin#develop
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/materik/homebridge-harmony-plugin.git
npm ERR!
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-26T12_30_11_719Z-debug.log

```

**Comment by mmutreja** [comment]
> @mensa84 try installing `npm install -g materik/homebridge-harmony-plugin#develop` and see if that works. I haven't tested it myself yet but will do when I get home.

It looks like we don't have access to the develop branch.

**Comment by materik** [comment]
ah. i wrote the wrong project name. should be:
```npm install -g materik/homebridge-harmonyhub-plugin#develop```
my bad

**Comment by mensa84** [comment]
It works again now! Thanks a lot to all!
So it does not need XMPP, right? Cause it currently is disabled on my hubs and the plugin is wokring anyway.

**Comment by materik** [comment]
it currently uses websockets

**Comment by mensa84** [comment]
Cool, thx!
Will there be a new release today?

**Comment by materik** [comment]
yes. will try it at home first and then make a new release.

**Comment by mensa84** [comment]
I did find another problem :(

I have 2 Harmony hubs.
The states of one hub are not refreshed in Homekit/Homebridge when I change the activity by Harmony Remote or Harmony App. The states are refreshed when I close the Home App on iPhone and re-open it. But that is a problem for automations. Why are the states of the second hub not recognized automatically like one the first one?

**Comment by mmutreja** [comment]
> ah. i wrote the wrong project name. should be: `npm install -g materik/homebridge-harmonyhub-plugin#develop`. my bad

Worked for me now.

**Comment by materik** [comment]
@mensa84 can you create a new issue for that. keep in mind that I do not have two hubs so i have a hard time testing it out so be specific. this fix is in `0.5.6` so i'm closing this issue. thanks everyone!

**Comment by mensa84** [comment]
Ok, I will do if that problem appears again. Since yesterday it is suddenly working without problems again... Strange...

**Comment by starlessblack** [comment]
It stopped working because Harmony pushed an update to all hubs that disabled the custom-enabled XMPP protocol, but they now give you a button in the Harmony app to re-enable XMPP protocol: https://community.logitech.com/s/question/0D55A00008OsX3CSAV/update-to-accessing-harmony-hubs-local-api-via-xmpp

The good thing was that this allowed me to get your plugin working again, @materik, the bad news is that I think the firmware update caused it to generated a new UID or something because now my Homebridge setup has two sets of Harmony switches--new, working ones and the old, now non-working ones.

I need to figure out how to get rid of the old accessory cache...

**Comment by acosmichippo** [comment]
i believe you can just delete /homebridge/accessories/cachedAccessories and restart.

**Comment by starlessblack** [comment]
Oh, good call, @acosmichippo . I was looking at the cachedAccessories file and dreading trying to figure out which harmony references to delete and which to leave. Thanks a bunch!
