### ISSUE TITLE
Possibility to replace Hub with no need to re-configure everything? (UUID in cachedAceessories)

### ISSUE THREAD

**Issue by mensa84** [materik/homebridge-harmonyhub-plugin#22]
Hello,

my Harmony Hub in the living room got defect and I want to go to replace it with a new one. Using the MyHarmony software it will be easy to restore the Logitech Harmony configuration on the hub.

But for the homebridge-harmony plugin the new hub will show up with a new UUID.

Which steps would be necessary to make homebridge-harmony plugin think, that the new hub is the same one as the old and so that I don't have to reconfigure everything in Homekit?

Would following be enough?

    * stop homebridge

    * replace old UUId in file "cachedAccessories" with UUID of the new Hub

    * start homebridge

I currently don't have received the new hub, therefore I can't test it.
I would thank you very much, if you could help me!

**Comment by materik** [comment]
I will look into how this might be done.

**Comment by materik** [comment]
I've been wondering about this. Not sure if the activites will change UUID too and in that case is it enough changing the uuid in cachedaccessories?

**Comment by mensa84** [comment]
I did re-add it in the meanwhile, so I can't say if that would have worked.

**Comment by materik** [comment]
Sorry for my lack in response. Since this is so old I would guess you have moved on and it's fine to close it. If not, please reopen this. Thanks!
