### ISSUE TITLE
Support different network

### ISSUE THREAD

**Issue by emes** [materik/homebridge-harmonyhub-plugin#27]
First, thanks so much for this!

To deal with Harmony hub being on a different network, I need to be able to pass an option to discover, like this in harmonyhub.js...

```let explorer = new Explorer(61991, { address: "192.168.38.255" });```

Would you consider adding a config option which defaults to {}?

https://github.com/AirBorne04/harmonyhub/blob/master/packages/discover/examples/discover-with-options.js

**Comment by materik** [comment]
yes. I have thought about this. will hopefully have the time to sit down with this soon.

**Comment by materik** [comment]
You can try out a fix for it by installing the particular feature branch like this:
`npm install -g materik/homebridge-harmonyhub-plugin#feature/config`. Read the README file in this brach which details how you can add explorer options. Let me know how it goes.

**Comment by emes** [comment]
Thanks for this and sorry I did not see sooner!  Works perfectly.  Only change was "address" rather than "ip".

```
diff --git a/README.md b/README.md
index 71d4300..1c9da22 100644
--- a/README.md
+++ b/README.md
@@ -33,7 +33,7 @@ Add this to your Homebridge `config.json` file:
             // Pass options to the HarmonyHub explorer function
             "explorer": {
                 "options": {
-                    "ip": "255.255.255.255"
+                    "address": "255.255.255.255"
                     // ...
                 }
             }
diff --git a/config.json.example b/config.json.example
index 6bad79b..b2024f4 100644
--- a/config.json.example
+++ b/config.json.example
@@ -4,8 +4,8 @@
     "config": {
         "explorer": {
             "options": {
-                "ip": "192.168.38.255"
-            },
+                "address": "192.168.38.255"
+            }
         },
         "hubs": [
             {
@@ -20,4 +20,4 @@
             }
         ]
     }
}
```
