### ISSUE TITLE
re-creates activities when restarting homebridge

### ISSUE THREAD

**Issue by nathsea** [materik/homebridge-harmonyhub-plugin#29]
HI I recently installed this plugin, works a treat. I have since rebooted my server a couple of times and it re-adds the activities every time as favourites and they appear on the front page ... a bit annoying, what am i doing wrong?

Cheers
Nath

**Comment by materik** [comment]
This shouldn't happen if you only restarts the homebridge. It should pick up the server settings from the cachedaccessories and persistent folders so if you haven removed them it should be fine. If you restart harmonyhub however it might get a new id which setups new activities in homekit. Please send the debug log on startup if it happens again.

**Comment by nathsea** [comment]
cheers, will do.

**Comment by nathsea** [comment]
Hi I’ve noticed the same issue again tonight , but it doesn’t re add the activities it just turns on the favourites switch so they repopulate the home page
Nath

**Comment by materik** [comment]
ok. can you post the log?

**Comment by nathsea** [comment]
Yeah ... maybe , is there an easy way to view it 😬 the logs page doesn’t show loads , so I need to enable more thorough logs ?

**Comment by nathsea** [comment]
![B7443F96-7D0D-4642-8984-F7BD6E82D9AA](https://user-images.githubusercontent.com/48316013/54640813-92c67c80-4a88-11e9-982d-5d8ac0d8f373.png)

**Comment by materik** [comment]
hehe. you can enable debug by running homebridge with -D flag. but what i can see from this log it seems to start the bridge correctly from cached accessories. do you see that issue with the activities being favorited after this?

**Comment by nathsea** [comment]
![B20FF210-4C28-4109-ACC4-E2940A42E40E](https://user-images.githubusercontent.com/48316013/54783384-2038d680-4c19-11e9-8dcc-55255673671e.png)
![D7F55F82-AFCE-46E2-A976-13066FEC06C6](https://user-images.githubusercontent.com/48316013/54783385-2038d680-4c19-11e9-849f-571ac1955038.png)
![D8123EDF-6157-430D-889D-51AEA18BF2EA](https://user-images.githubusercontent.com/48316013/54783386-2038d680-4c19-11e9-827e-79b9fa8e8b68.png)
![5FDDEE20-F0F8-45C8-9027-1D42EF5AAFE6](https://user-images.githubusercontent.com/48316013/54783387-2038d680-4c19-11e9-873a-2b84590a31cb.png)

Hi hope this works ?? Yep it’s just done it again

**Comment by jelzeinvmw** [comment]
I'm seeing the same issue above -- activities reset to defaults after restarting homebridge. Consistent, every time.

Log error: [8/14/2019, 10:40:54 PM] [homebridge-harmonyhub-plugin] {HarmonyHub} handleError: TypeError: Cannot read property 'result' of undefined
    at wsClient.sendRequest.then (/homebridge/node_modules/homebridge-harmonyhub-plugin/node_modules/@harmonyhub/client-ws/dist/harmonyclient.js:134:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by materik** [comment]
Sorry for my lack in response. Since this is so old I would guess you have moved on and it's fine to close it. If not, please reopen this. Thanks!
