### ISSUE TITLE
HomeKit not recognizing state change for automation

### ISSUE THREAD

**Issue by starlessblack** [materik/homebridge-harmonyhub-plugin#30]
I have an automation that dims some lights when launching a Harmony activity, but it seems to have ceased working entirely when I use the Harmony physical remote or app to launch activity. When I use the Home app or Siri/HomeKit, it works as expected. This /seems/ to have coincided with either my move from the original homebridge-harmonyhub plugin to yours or when you moved from the xmpp to the web sockets version.

**Comment by materik** [comment]
Sorry for my lack in response. Since this is so old I would guess you have moved on and it's fine to close it. If not, please reopen this. Thanks!
