### ISSUE TITLE
No log entries after Initializing

### ISSUE THREAD

**Issue by GavanWilhite** [materik/homebridge-harmonyhub-plugin#32]
When I start up homebridge, this is the only entry I get from harmonyhub-plugin:

[6/30/2019, 4:35:18 PM] [homebridge-harmonyhub-plugin] Initializing HarmonyHub platform...
Setup Payload:
X-HM://0023ISYWYME6H
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
...

I don't see any additional entries, and while homebridge is a connected device in Home, I have no activities from Harmony to add in the home app.

**Comment by materik** [comment]
Sorry for my lack in response. Since this is so old I would guess you have moved on and it's fine to close it. If not, please reopen this. Thanks!

**Comment by GavanWilhite** [comment]
If you have thoughts, I’d be keen

**Comment by materik** [comment]
can you post your config file.
