### ISSUE TITLE
Removing Previous Activities

### ISSUE THREAD

**Issue by jimmyd222** [materik/homebridge-harmonyhub-plugin#33]
I've been trying to remove an activity I no longer use and am stumped as for the best way to do this. I've tried to remove the platform from config.json, then uninstall the plugin, but the activity is still there. Also seems no way to just delete the switch from the Home App. Any suggestions would be appreciated!

**Comment by BAngel87** [comment]
Did you find a solution?

**Comment by materik** [comment]
Try removing it from accessories

**Comment by starlessblack** [comment]
Hey there, @materik, what exactly do you mean by this? I've got an old stale activity I can't seem to remove either. Thanks!
