### ISSUE TITLE
Can`t get any HarmonyHub activities available in HomeKit

### ISSUE THREAD

**Issue by ZimboGitHub** [materik/homebridge-harmonyhub-plugin#40]
Hi materik,
i have an problem to get the activities out of my HarmonyHub into the Homekit.
I installed it like descripted and your plugin will found my HarmonyHub, but that's it.
In the protokoll i saw following lines: and ther a "TypeError"

[11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
[11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} <3b67236a-ad0d-4003-9b6c-2e57a09397b6> <HarmonyHub>
[11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {Plugin} loadAccessories: **TypeError: Cannot read property 'name' of undefined**
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61
    at arrayMap (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:9580:14)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:43:13
    at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Did i something wrong or is it an issue.
It will be great if you could help me.
Best regards
Frank 

Some Info about my System:
Homebridge v1.1.6 
homebridge-harmonyhub-plugin v0.5.8 
Platform: linux
Architecture: arm
CPUs: 4
Speed: 1200 MHz
Model: ARMv7 Processor rev 4 (v7l)
RAM: 926 MB 
System uptime: 2 T. 20:59:09
Node.js: v10.23.0
NPM: 6.14.8
adapters count: 321
Uptime: 2 T. 20:58:52

**Comment by Tramway4385** [comment]
Hi

i have the same type error :-(

**Comment by WinterC15** [comment]
I'm having the same error. Does anyone know what we may have done wrong?

**Comment by swoogi** [comment]
just comment out lib/plugin.js:51
the line is only for logging
it works for me

**Comment by swoogi** [comment]
> I'm having the same error. Does anyone know what we may have done wrong?



> Hi materik,
> i have an problem to get the activities out of my HarmonyHub into the Homekit.
> I installed it like descripted and your plugin will found my HarmonyHub, but that's it.
> In the protokoll i saw following lines: and ther a "TypeError"
> 
> [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
> [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} <3b67236a-ad0d-4003-9b6c-2e57a09397b6>
> [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {Plugin} loadAccessories: **TypeError: Cannot read property 'name' of undefined**
> at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61
> at arrayMap (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:639:23)
> at Function.map (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:9580:14)
> at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:43:13
> at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
> at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
> at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
> at processTicksAndRejections (internal/process/task_queues.js:75:11)
> 
> Did i something wrong or is it an issue.
> It will be great if you could help me.
> Best regards
> Frank
> 
> Some Info about my System:
> Homebridge v1.1.6
> homebridge-harmonyhub-plugin v0.5.8
> Platform: linux
> Architecture: arm
> CPUs: 4
> Speed: 1200 MHz
> Model: ARMv7 Processor rev 4 (v7l)
> RAM: 926 MB
> System uptime: 2 T. 20:59:09
> Node.js: v10.23.0
> NPM: 6.14.8
> adapters count: 321
> Uptime: 2 T. 20:58:52


just comment out lib/plugin.js:51
the line is only for logging
it works for me

**Comment by ZimboGitHub** [comment]
> 
> 
> > I'm having the same error. Does anyone know what we may have done wrong?
> 
> > Hi materik,
> > i have an problem to get the activities out of my HarmonyHub into the Homekit.
> > I installed it like descripted and your plugin will found my HarmonyHub, but that's it.
> > In the protokoll i saw following lines: and ther a "TypeError"
> > [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
> > [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} <3b67236a-ad0d-4003-9b6c-2e57a09397b6>
> > [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {Plugin} loadAccessories: **TypeError: Cannot read property 'name' of undefined**
> > at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61
> > at arrayMap (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:639:23)
> > at Function.map (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:9580:14)
> > at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:43:13
> > at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
> > at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
> > at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
> > at processTicksAndRejections (internal/process/task_queues.js:75:11)
> > Did i something wrong or is it an issue.
> > It will be great if you could help me.
> > Best regards
> > Frank
> > Some Info about my System:
> > Homebridge v1.1.6
> > homebridge-harmonyhub-plugin v0.5.8
> > Platform: linux
> > Architecture: arm
> > CPUs: 4
> > Speed: 1200 MHz
> > Model: ARMv7 Processor rev 4 (v7l)
> > RAM: 926 MB
> > System uptime: 2 T. 20:59:09
> > Node.js: v10.23.0
> > NPM: 6.14.8
> > adapters count: 321
> > Uptime: 2 T. 20:58:52
> 
> just comment out lib/plugin.js:51
> the line is only for logging
> it works for me

Hi Swogi,
thanks for your hint :-)
and a happy new year ;-)
But I'am a newby. Where i have to comment out? 
What path ?
-->/usr/lib/node_modules/homebridge-harmonyhub-plugin ??? correct ??

Which  file ? --> i could not file a line for "lib/plugin.js:51"
How to  comment out --> "//" ???

Here are my harmony config out off the plugin: (of course xx are place holders)
{
    "platform": "HarmonyHub",
    "name": "HarmonyHub",
    "config": {
        "explorer": {
            "options": {
                "address": "192.168.x.xxx"
            }
        }
    }
}

Best regards
Frank

**Comment by swoogi** [comment]
> > > I'm having the same error. Does anyone know what we may have done wrong?
> > 
> > 
> > > Hi materik,
> > > i have an problem to get the activities out of my HarmonyHub into the Homekit.
> > > I installed it like descripted and your plugin will found my HarmonyHub, but that's it.
> > > In the protokoll i saw following lines: and ther a "TypeError"
> > > [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} Found <1> hubs
> > > [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {HarmonyHub} <3b67236a-ad0d-4003-9b6c-2e57a09397b6>
> > > [11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {Plugin} loadAccessories: **TypeError: Cannot read property 'name' of undefined**
> > > at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61
> > > at arrayMap (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:639:23)
> > > at Function.map (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/lodash/lodash.js:9580:14)
> > > at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:43:13
> > > at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:37:12)
> > > at /usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/promise/lib/core.js:123:15
> > > at flush (/usr/lib/node_modules/homebridge-harmonyhub-plugin/node_modules/asap/raw.js:50:29)
> > > at processTicksAndRejections (internal/process/task_queues.js:75:11)
> > > Did i something wrong or is it an issue.
> > > It will be great if you could help me.
> > > Best regards
> > > Frank
> > > Some Info about my System:
> > > Homebridge v1.1.6
> > > homebridge-harmonyhub-plugin v0.5.8
> > > Platform: linux
> > > Architecture: arm
> > > CPUs: 4
> > > Speed: 1200 MHz
> > > Model: ARMv7 Processor rev 4 (v7l)
> > > RAM: 926 MB
> > > System uptime: 2 T. 20:59:09
> > > Node.js: v10.23.0
> > > NPM: 6.14.8
> > > adapters count: 321
> > > Uptime: 2 T. 20:58:52
> > 
> > 
> > just comment out lib/plugin.js:51
> > the line is only for logging
> > it works for me
> 
> Hi Swoogi,
> thanks for your hint :-)
> and a happy new year ;-)
> But I'am a newby. Where i have to comment out?
> What path ?
> -->/usr/lib/node_modules/homebridge-harmonyhub-plugin ??? correct ??
> 
> Which file ? --> i could not find a line for "lib/plugin.js:51"
> How to comment out --> "//" ???
> 
> Here are my harmony config out off the plugin: (of course xx are place holders)
> {
> "platform": "HarmonyHub",
> "name": "HarmonyHub",
> "config": {
> "explorer": {
> "options": {
> "address": "192.168.x.xxx"
> }
> }
> }
> }
> 
> Best regards
> Frank

Ok, the path is in your log
third line of below
...
[11.12.2020, 15:01:22] [homebridge-harmonyhub-plugin] {Plugin} loadAccessories: TypeError: Cannot read property 'name' of undefined
at /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61
...

SO, you must fix /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js:51:61

51th line of the file /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib/plugin.js

You can just comment out the line with '//'
51th line is just for logging...
I hope this can help...

**Comment by ZimboGitHub** [comment]
thank's a lot for your quick response. It gave me the direction.
Out commenting the line #51 fixed the problem and my Harmony acctions are present now 👍 
But for realy beginers without any Unix/Linux knowledge i wrote a short howto:

connect to your Homebridge e.g. Raspberry by any SSH-Terminal program e.g. "Putty"   --> "https://www.putty.org/"
login : pi
User : raspberry

"cd /usr/lib/node_modules/homebridge-harmonyhub-plugin/lib"  --> Jump into directory
"sudo chmod -v 777 plugin.js"                                                      --> Set write permission for user sudo
"vi +51 plugin.js"                                                                          --> Open file "plugin.js" by vi editor and jump to line 51
"Insert"                                                                                         --> Press "Insert" or "Einfg" for german people ;-) 
"//"                                                                                               --> Comment out line 51
"ESC"                                                                                            --> Press "ESC"
":wq!"                                                                                            --> Save, write the file and exit vi
"sudo systemctl restart homebridge"                                             --> Restart Hombridge
"sudo -n journalctl -o cat -n 500 -f -u homebridge"                      --> Open Homebridge Log and check the result 

Best regards Frank
