### ISSUE TITLE
Hub is rebooting (red led) more than before

### ISSUE THREAD

**Issue by DJay-X** [materik/homebridge-harmonyhub-plugin#6]
@materik First of all thanks for you work and sharing.
I use your plugin a couple of days now and it might be a coincidence that I noticed that my Hub is showing the red LED (reboot?) more often now. In the past I only did notice this very rarely.
Can this be in relation? 

Also I noticed that changing the actual state is slower than before with the "old" (homebridge-harmonyhub v0.3.0-alpha.2). As shown in the screenshot both, Apple TV and Smart TV looks like on. 
After a refresh of the App (Eve) it switches to the correct one, only one action on.

Maybe all a coincidence but I want to point it to you if there is something you want to investigate.
If there is anything I can help testing, please of course let me know.

Thanks again

![napkin 12 11 18 6 30 51 pm](https://user-images.githubusercontent.com/3874239/48364604-19b5b380-e6a9-11e8-909b-552d247dff74.png)

**Comment by materik** [comment]
Great. Thanks for helping me improve the project. I can have a look.

**Comment by materik** [comment]
@DJay-X after installing the fix to #3 (v0.5.0) could you verify this this is still an issue. Thanks!

**Comment by DJay-X** [comment]
@materik Thanks for your ongoing work. Unfortunately I can't test your plugin at the moment. But I will do as soon as possible and give a feedback.
Can you explain what the difference/advantage is of your plugin and @nicoduj https://github.com/nicoduj/homebridge-harmony ?
And have you guys ever considered to work together on one plugin? You both seem to have great knowledge and together is always better, isn't it? ;)
Thanks again.

**Comment by DJay-X** [comment]
Closed because can't reproduce anymore. In case of this issue happens again, I'll reopen.
Thx.
